export default {
  STOP_LOADING: "STOP_LOADING",
  START_LOADING: "START_LOADING",
  START_SUCCESS: "START_SUCCESS",
  STOP_SUCCESS: "STOP_SUCCESS",
  OPEN_SIDEBAR: "OPEN_SIDEBAR",
  LOAD_BOT_NUMS: "LOAD_BOT_NUMS",

  COMPANY_LIST: "COMPANY_LIST",
  COMPANY_DETAIL: "COMPANY_DETAIL",
  FEE_LIST: "FEE_LIST",
  LORD_LIST: "LORD_LIST"
};
